
create table if not exists orders
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id int REFERENCES customer(id) ON DELETE CASCADE NOT NULL,
    restaurant_id int REFERENCES restaurant(id) ON DELETE CASCADE NOT NULL,
    courier_id int REFERENCES courier(id) ON DELETE SET NULL,
    status varchar(100) NOT NULL,
    order_date timestamp
);