
create table if not exists customer
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(50) NOT NULL,
    phone varchar(20) UNIQUE NOT NULL,
    email varchar(50) UNIQUE NOT NULL
);