
create table if not exists restaurant
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) UNIQUE NOT NULL,
    address varchar(100) NOT NULL,
    status varchar(50) NOT NULL,
    coordinates varchar(50) NOT NULL
);