
create table if not exists order_item
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id int REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    restaurant_menu_item_id int REFERENCES restaurant_menu_item(id) ON DELETE CASCADE NOT NULL,
    price int NOT NULL,
    quantity int NOT NULL
);