
create table if not exists courier
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(50) NOT NULL,
    phone varchar(20) UNIQUE NOT NULL,
    status varchar(50) NOT NULL,
    coordinates varchar(50)
);