INSERT INTO restaurant_menu_item (restaurant_id, name, price, image, description)
VALUES (3, 'Стейк Рибай Прайм', 890,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\ribai.jpg',
        'Толстый край мраморной говядины зернового откорма высшей категории'),
       (3, 'Тартар Топ Блейд ', 590,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\tartar.jpg',
        'Подготовленная свежая мраморная говядина'),
       (3, 'Бургер Блэк Ангус', 399,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\black_angus.jpg',
        'Домашняя булочка, пряный майонез, томатный соус, лук'),
       (2, 'Картофель фри', 270,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\fri.jpg',
        'Картофель фри во фритюре'),
       (2, 'Луковые кольца', 300,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\kolca.jpg',
        'Вкусные луковые кольца'),
       (2, 'Сырные шарики', 330,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\shariki.jpg',
        'Сырные шарики из моцареллы в панировке'),
       (1, 'Карпаччо из мраморной говядины', 390,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\karpacho.jpg',
        'Тонкие слайсы мраморной говядины с бальзамическим'),
       (1, 'Лосось, спаржа, зеленый горошек', 690,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\sparja.jpg',
        'Филе лосося со спаржей, пюре из зеленого горошка'),
       (1, 'Нисуаз с тунцом', 450,
        'C:\Users\Администратор\Desktop\foodService\kitchen-service\src\main\resources\images\nisuaz.jpg',
        'Микс салат с тунцом, печеным картофелем, томатами');