spring:
  application:
    name: kitchen-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_service_db
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
  endpoint:
    health:
      show-details: ALWAYS